In [1]:
import numpy as np

### Vector operations

In [2]:
u = np.array([2, 4, 5, 6])

In [3]:
2 * u

array([ 4,  8, 10, 12])

In [4]:
v = np.array([1, 0, 0, 2])

In [5]:
u + v

array([3, 4, 5, 8])

### Multiplications

#### vector-vector

In [6]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0] ## make sure the vectors have the same size
    
    n = u.shape[0]
    
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [7]:
vector_vector_multiplication(u, v)

14.0

In [8]:
u.dot(v)

14

#### matrix-vector

In [9]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

In [10]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0] #columns in matrix = rows in vector
    
    num_rows = U.shape[0]
    
    result_vector = np.zeros(num_rows)
    
    for i in range(num_rows):
        result_vector[i] = vector_vector_multiplication(U[i], v)
    
    return result_vector

In [11]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [12]:
U.dot(v)

array([14,  5,  5])

#### matrix-matrix

In [13]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])

In [14]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [15]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [16]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

### Identity Matrix

In [17]:
I = np.eye(3)

In [18]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [20]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

### Matrix Inverse

Only square matrizes have inverses

In [28]:
# get the first 3 rows of matrix V
V[[0, 1, 2]]

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [23]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [24]:
# compute the matrix inverse of V square matrix
np.linalg.inv(Vs)

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [25]:
Vs_inv = np.linalg.inv(Vs)

In [26]:
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [29]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])