In [2]:
import pandas as pd
import numpy as np

### Q1: version of numpy

In [4]:
np.__version__

'1.18.5'

**Get the data**

In [6]:
pwd

'C:\\Users\\Geral\\Desktop\\VSCODE\\ml_zoomcamp\\01_intro'

In [8]:
data = pd.read_csv('data.csv')

In [9]:
data

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

### Q2: How many records are in the dataset?

In [11]:
data.shape

(11914, 16)

### Q3: Who are the most frequent car manufacturers (top-3) according to the dataset?

In [14]:
data['Make'].value_counts()[0:3]

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

### Q4: What's the number of unique Audi car models in the dataset?

In [18]:
data[data['Make'] == 'Audi']['Model'].nunique()

34

### Q5: How many columns in the dataset have missing values?

In [26]:
data.isnull().sum()[data.isnull().sum() > 0]

Engine Fuel Type       3
Engine HP             69
Engine Cylinders      30
Number of Doors        6
Market Category     3742
dtype: int64

### Q6: New median?

 - Find the median value of "Engine Cylinders" column in the dataset.
 
 - Next, calculate the most frequent value of the same "Engine Cylinders".

 - Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.

 - Now, calculate the median value of "Engine Cylinders" once again.

**Has it changed?**

In [32]:
engine_cylinders_median = data['Engine Cylinders'].median()

In [38]:
engine_cylinders_median

6.0

In [36]:
data['Engine Cylinders'].describe()

count    11884.000000
mean         5.628829
std          1.780559
min          0.000000
25%          4.000000
50%          6.000000
75%          6.000000
max         16.000000
Name: Engine Cylinders, dtype: float64

In [34]:
engine_cylinders_mode = data['Engine Cylinders'].mode()

In [39]:
engine_cylinders_mode

0    4.0
dtype: float64

In [37]:
data['Engine Cylinders'].value_counts()

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [48]:
data.head(2)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650

In [53]:
data['Engine Cylinders'].fillna(4, inplace = True)

In [54]:
data['Engine Cylinders'].isnull().sum()

0

In [55]:
data['Engine Cylinders'].median()

6.0

### Q7: Value of w
1. Select all the "Lotus" cars from the dataset.

2. Select only columns "Engine HP", "Engine Cylinders".

3. Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).

4. Get the underlying NumPy array. Let's call it X.

5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

6. Invert XTX.

7. Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].

8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

9. **What's the value of the first element of w?**

In [58]:
lotus = data[data['Make'] == 'Lotus'][['Engine HP', 'Engine Cylinders']]

lotus

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0
3917      189.0               4.0
3918      217.0               4.0
3919      217.0               4.0
4216      350.0               8.0
4217      350.0               8.0
4218      350.0               8.0
4257      400.0               6.0
4258      400.0               6.0
4259      276.0               6.0
4260      276.0               6.0
4261      276.0               6.0
4262      345.0               6.0
4263      345.0               6.0
4264      276.0               6.0
4265      345.0               6.0
4266      276.0               6.0
4267      345.0               6.0
4268      276.0               6.0
4292      257.0               4.0
4293      240.0               4.0
4294      240.0               4.0
4295      240.0               4.0
4296      257.0               4.0
4297      257.0               4.0

In [64]:
# remove duplicates
lotus = lotus.drop_duplicates()
lotus

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [65]:
# df in form of an array
X = lotus.values

X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [68]:
# matrix-matrix multiplication between the transpose of X and X

XTX = X.T.dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [71]:
# get the invert of the transpose
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [74]:
#create an array y
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [75]:
#multiply XTX_inv with the X.T
XTX_inv.dot(X.T)

array([[-1.31950096e-03,  2.84443321e-04,  2.29134897e-04,
        -4.18763778e-03,  4.46417989e-03, -2.39406462e-03,
         1.42221660e-03,  2.44147184e-03,  1.50122864e-03],
       [ 8.60893170e-02,  7.36567735e-04,  3.67976598e-03,
         2.54588185e-01, -2.13748621e-01,  1.51207962e-01,
        -5.18727169e-02, -1.14048164e-01, -6.40137937e-02]])

In [77]:
#multiply the previous result with y and called it w
w = XTX_inv.dot(X.T).dot(y)
w

array([  4.59494481, -63.56432501])

In [78]:
w[0]

4.594944810094551